name: SwagLabs Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v7

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v7
